name: draft-release

on:
  push:
    tags: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target:
        - x86_64-pc-windows-msvc
        - x86_64-unknown-linux-gnu
        extra: ['bin']
        include:
        - target: x86_64-pc-windows-msvc
          extra: 'bin'
          os: windows-latest
          target_rustflags: ''
          output: cahirc.exe
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
          target_rustflags: ''
          output: cahirc
      
  
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      - name: Build with Cargo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Zip the executable
        uses: papeloto/action-zip@v1
        with:
          files: 'target/${{ matrix.target }}/release/${{ matrix.output }}'
          dest: 'cahirc-${{ matrix.target }}.zip'
      # REF: https://github.com/marketplace/actions/gh-release
      - name: Publish Archive
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: true
          files: 'cahirc-${{ matrix.target }}.zip'
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
